site_name: ADR MKDOCS sandbox
#site_url: https://www...
site_description: >-
  multi line
  description
site_author: author
copyright: Copyright &copy; 2021 - 2022 user

#repo_url: https://github.com/...

strict: true                      # warns will stop processing

theme:
  name: material
  #font: false                    # disable loading of Google Fonts
  #logo: assets/images/logo.png
  #favicon: assets/images/favicon.png
  custom_dir: overrides           # theme override directory
  features:
    - navigation.instant
    - navigation.tracking         # updates the URL bar
    - navigation.tabs             # first level menu on top
    - navigation.tabs.sticky
#    - navigation.indexes
    - navigation.sections
    - navigation.top              # back to top button

nav:
  - Home: 'README.md'
  - Archtectural Decisions:
    - ...
  - Categories: 'categories.md'
  - License: 'license.md'
  - Export: '/print_page/'

# mostly recommended extensions by Material Theme
markdown_extensions:
  - meta                          # Front Matter
  - attr_list
  - def_list
  - tables                        # Tables/DataTables
  - footnotes                     # Footnotes
  - abbr                          # Abbreviations
  - admonition                    # Admonition
  - toc:
      permalink: true

  # python markdown extensions
  - pymdownx.snippets             # Abbreviations
  - pymdownx.details              # Admonition
  - pymdownx.superfences:         # Admonition & Diagrams
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:            # def_list
      custom_checkbox: true
  - pymdownx.betterem:
      smart_enable: all


plugins:
  - tags:
      tags_file: categories.md    # generate linkable tags/taxonomy in front matter
  - search
  - awesome-pages
  - with-pdf:
      author: none
      copyright: none
  - print-site
#  - privacy:                     # **PREMIUM**: needs to be at the end of plugins list
#      download: !ENV [DOWNLOAD, false]


